/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef CORTO_HTTPROUTER_BAKE_CONFIG_H
#define CORTO_HTTPROUTER_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <corto.httpserver>
#include <corto.x>
#include <corto>
#include <corto.httpserver.c>
#include <corto.x.c>
#include <corto.c>
#include <bake.util>

/* Headers of private dependencies */
#ifdef CORTO_HTTPROUTER_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#if CORTO_HTTPROUTER_IMPL && defined _MSC_VER
#define CORTO_HTTPROUTER_EXPORT __declspec(dllexport)
#elif CORTO_HTTPROUTER_IMPL
#define CORTO_HTTPROUTER_EXPORT __attribute__((__visibility__("default")))
#elif defined _MSC_VER
#define CORTO_HTTPROUTER_EXPORT __declspec(dllimport)
#else
#define CORTO_HTTPROUTER_EXPORT
#endif

#endif

